language: node_js
node_js:
  - 6.10.3
  - 8.0.0
script:
  - npm run lint
  - npm test
  - npm run build
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: mr5.simple@gmail.com
  api_key:
    secure: "RLbwKQjjTmN1mVu/joG8lkllZIqr/r8e4/HiylgCKgRR/ynGtw7+LI5qYpoMTpwSdkeweZD1/YAFjNGv24I2iE+BKzU2AVYW4ST6dAvapZp4xP7te0nTuDBEXbrrnu7REhA5PfpepEIqzQkMT2GWarNM7CNDrkWd21gINaHHUUtI59TwGQOO3uCbIylT7xfkuSNPasNdajBculhciJvaE48Upqdxlx+vaQ/pRMYb4p6UyvOlcKIU3U5uH+iZRwSZHAPAnjBm2MzgMvcFxZwagWizNH9GhIajPCXWEGTUa+3YnuPcjruK5Wc3FXHDaNm7KXKSc914cA2fwdktDKcPoFNlm6D6NKqof/bSB8mtPQVFT/7QiN+ZAcYtMHTgXo5KCOHx8FJlkKy2jwJ+EpCytgatz5dg+phcDcBeNcm0u9/rAxvabdyn6lm/1CtQ8PiHc3LvwmbMzuU8yNbbdlJ4q6u1v3l+Ky++VYlRY7cH0MBcGGsk2lEQq8b8oYGKbvshoThsO+5vPijYLYVjt1MQ6OteAX+ub7WpU4molcwzwfpxJPryL+9a5XA4RPCtBzsFZXInis/a7BUSVufplt00J1I/8piWRd1wGceHbEw5qNENm+FtX/2SsQzaC99iHbRcN1cH8HwOxG4EcwCnPfFptgD1WNbtV8uxnxYnFGCRb1s="
  on:
    tags: true